digital_8848/digital_8848/doctype/expertise/expertise.js
digital_8848/digital_8848/doctype/expertise/expertise.json
digital_8848/digital_8848/doctype/expertise/expertise.py
digital_8848/digital_8848/doctype/expertise/test_expertise.py
digital_8848/digital_8848/doctype/expertise_detail/expertise_detail.json
digital_8848/digital_8848/doctype/expertise_detail/expertise_detail.py
digital_8848/digital_8848/doctype/process_detail/process_detail.json
digital_8848/digital_8848/doctype/process_detail/process_detail.py
digital_8848/digital_8848/doctype/services_detail/services_detail.json
digital_8848/digital_8848/doctype/services_detail/services_detail.py
digital_8848/digital_8848/doctype/why_choose_8848/why_choose_8848.json
digital_8848/digital_8848/doctype/why_choose_8848/why_choose_8848.py

Created Expertise doctype and child tables

feat: Created Expertise doctype and child tables

---

digital_8848/digital_8848/doctype/expertise/expertise.json
digital_8848/digital_8848/doctype/logo/logo.js
digital_8848/digital_8848/doctype/logo/logo.json
digital_8848/digital_8848/doctype/logo/logo.py
digital_8848/digital_8848/doctype/logo/test_logo.py

feat: created logo doctype

---

digital_8848/digital_8848/doctype/expertise/expertise.json
digital_8848/digital_8848/doctype/faqs/faqs.json
digital_8848/digital_8848/doctype/faqs/faqs.py

added case study and faqs in expertise

feat: added case study and faqs in expertise

---

digital_8848/digital_8848/doctype/logo/api/logo.py

feat: logo details api

---

digital_8848/digital_8848/doctype/expertise/expertise.json

added subtitle field in expertise

fix: added subtitle field in expertise

---

digital_8848/digital_8848/doctype/expertise/expertise.json

added logo and sequence field in expertise

fix: added logo and sequence field in expertise

---

digital_8848/digital_8848/doctype/expertise/api/expertise_details.py

feat: expertise_details_api

---

digital_8848/digital_8848/doctype/expertise/api/expertise_listing.py
digital_8848/digital_8848/doctype/expertise/expertise.json

Created Expertise Listing API.
Added Short Description Field.

feat: expertise listing api

---

commitlint.config.js

feat: added commitlint.config.js file

---

digital_8848/digital_8848/doctype/case_study/api/case_study_details.py
digital_8848/digital_8848/doctype/case_study/api/case_study_listing.py
digital_8848/digital_8848/doctype/case_study/case_study.js
digital_8848/digital_8848/doctype/case_study/case_study.json
digital_8848/digital_8848/doctype/case_study/case_study.py
digital_8848/digital_8848/doctype/case_study/test_case_study.py

Case study details and listing api

feat: case study details and listing api

---

digital_8848/digital_8848/doctype/insights/api/insights_details.py
digital_8848/digital_8848/doctype/insights/api/insights_listing.py
digital_8848/digital_8848/doctype/insights/insights.js
digital_8848/digital_8848/doctype/insights/insights.json
digital_8848/digital_8848/doctype/insights/insights.py
digital_8848/digital_8848/doctype/insights/test_insights.py

Insights listing and details api

feat: insights listing and details api

---

digital_8848/digital_8848/doctype/case_study/api/case_study_listing.py
digital_8848/digital_8848/doctype/case_study/case_study.json

fix: updated type key in case study listing api

---

digital_8848/digital_8848/doctype/case_study/api/case_study_details.py
digital_8848/digital_8848/doctype/case_study/case_study.json

Updated case study doctype fields.
Updated case study details api.

fix: updated case study fields and details api

---

digital_8848/digital_8848/doctype/capabilities_detail/capabilities_detail.json
digital_8848/digital_8848/doctype/capabilities_detail/capabilities_detail.py
digital_8848/digital_8848/doctype/functionality_detail/functionality_detail.js
digital_8848/digital_8848/doctype/functionality_detail/functionality_detail.json
digital_8848/digital_8848/doctype/functionality_detail/functionality_detail.py
digital_8848/digital_8848/doctype/functionality_detail/test_functionality_detail.py
digital_8848/digital_8848/doctype/insights/api/insights_details.py
digital_8848/digital_8848/doctype/insights/insights.json
digital_8848/digital_8848/doctype/integration_detail/integration_detail.json
digital_8848/digital_8848/doctype/integration_detail/integration_detail.py
digital_8848/digital_8848/doctype/why_choose_8848/why_choose_8848.json

updated insights fields and details api

fix: updated insights fields and details api

---

digital_8848/digital_8848/doctype/advantages/advantages.json
digital_8848/digital_8848/doctype/expertise/api/expertise_details.py
digital_8848/digital_8848/doctype/expertise/api/expertise_listing.py
digital_8848/digital_8848/doctype/expertise/expertise.json
digital_8848/digital_8848/doctype/faqs/faqs.json
digital_8848/digital_8848/doctype/process_detail/process_detail.json

Updated url, sequence and background image key in expertise api.

fix: updated url, sequence and background image key in expertise api

---

digital_8848/digital_8848/doctype/meta_tags/api/meta_tags.py
digital_8848/digital_8848/doctype/meta_tags/meta_tags.js
digital_8848/digital_8848/doctype/meta_tags/meta_tags.json
digital_8848/digital_8848/doctype/meta_tags/meta_tags.py
digital_8848/digital_8848/doctype/meta_tags/test_meta_tags.py

feat: meta tags api

---

digital_8848/digital_8848/doctype/about_us/about_us.json
digital_8848/digital_8848/doctype/about_us/api/get_about_us_detail.py

Added industry tab and updated API response.

feat: added industry tab and updated api response

---

digital_8848/digital_8848/doctype/advantages/advantages.json
digital_8848/digital_8848/doctype/banner_detail/banner_detail.json
digital_8848/digital_8848/doctype/capabilities_detail/capabilities_detail.json
digital_8848/digital_8848/doctype/certified_partner_table/certified_partner_table.json
digital_8848/digital_8848/doctype/certified_partners/certified_partners.json
digital_8848/digital_8848/doctype/client_details/client_details.json
digital_8848/digital_8848/doctype/faqs/faqs.json
digital_8848/digital_8848/doctype/functionality_detail/functionality_detail.json
digital_8848/digital_8848/doctype/global_delivery_details/global_delivery_details.json
digital_8848/digital_8848/doctype/integration_detail/integration_detail.json
digital_8848/digital_8848/doctype/our_value_details/our_value_details.json
digital_8848/digital_8848/doctype/process_detail/process_detail.json
digital_8848/digital_8848/doctype/services_detail/services_detail.json
digital_8848/digital_8848/doctype/why_choose_8848/why_choose_8848.json

Enabled "In List View" for child table fields.
Changed the type of Attach Image fields to Attach.

fix: enabled in list view for child table fields

---

digital_8848/digital_8848/doctype/industry/api/industry.py

Changed the search parameter from title to slug.

fix: changed the search parameter from title to slug

---

digital_8848/digital_8848/doctype/about_us/about_us.json

Added designation field in founder tab

feat: added designation field in founder tab

---

digital_8848/digital_8848/doctype/case_study/api/case_study_home_page.py
digital_8848/digital_8848/doctype/case_study/case_study.json
digital_8848/digital_8848/doctype/case_study/case_study.py
digital_8848/digital_8848/doctype/expertise/api/expertise_details.py
digital_8848/digital_8848/doctype/expertise/expertise.json
digital_8848/digital_8848/doctype/tag_detail/tag_detail.json
digital_8848/digital_8848/doctype/tag_detail/tag_detail.py
digital_8848/digital_8848/doctype/why_choose_8848/why_choose_8848.json

Added a Tab "Tag Details" in Case Study Doctype.
Created a Child Table "Tag Detail" in Case Study Doctype.
Created a Checkbox "Display On Home Page" in Case Study Doctype.
Created a new API for displaying Case Study on Home Page.
Added Image Field in "Why Choose 8848" Child Table in Expertise Doctype.
Added a Tab "Expertise Details" in Expertise Doctype.
Updated all the API responses accordingly.

fix: multiple changes

---

digital_8848/digital_8848/doctype/case_study/api/case_study_listing.py

Updated "Tag detail" key in Case Study Listing API

fix: updated tag detail key in case_study_listing api

---

digital_8848/digital_8848/doctype/expertise/api/expertise_listing.py
digital_8848/digital_8848/doctype/industry/api/industry.py

Sorted the response of expertise listing and industry by sequence

fix: sorted listings by sequence

---

digital_8848/digital_8848/doctype/expertise/api/expertise_details.py
digital_8848/digital_8848/doctype/insights/api/insights_details.py

adding data of service_details_info child table of service details doctype in api response

feat: adding data of service_details_info child table of service details doctype in api response

---

digital_8848/digital_8848/doctype/case_study/case_study.json

changed type select field to linked industry master

fix: changed type select field to linked industry master

---

digital_8848/digital_8848/doctype/case_study/api/case_study_details.py
digital_8848/digital_8848/doctype/expertise/api/expertise_details.py
digital_8848/digital_8848/doctype/industry/api/industry.py
digital_8848/digital_8848/doctype/insights/api/insights_details.py

Added "title" search parameter.

fix: added title search parameter in details api

---

digital_8848/digital_8848/doctype/case_study/api/case_study_details.py
digital_8848/digital_8848/doctype/case_study/case_study.py
digital_8848/digital_8848/doctype/insights/api/insights_details.py

Validation and Api Fixes for Case Study and Impact

fix: Validation and Api Fixes for Case Study and Impact

---

digital_8848/digital_8848/doctype/case_study/case_study.py

Field Name  Issue Fix in Validation Condition

fix:Validation Issue in Case Study

---

digital_8848/digital_8848/doctype/expertise/api/home.py
digital_8848/digital_8848/doctype/expertise/expertise.json

Platform language

---

digital_8848/digital_8848/doctype/expertise/api/home.py

fix: sequence in technology API

---

digital_8848/digital_8848/doctype/expertise/api/expertise_details.py

added case study in expertise api

fix: added case study in expertise api

---

digital_8848/digital_8848/doctype/case_study/api/case_study_details.py
digital_8848/digital_8848/doctype/case_study/api/case_study_home_page.py
digital_8848/digital_8848/doctype/case_study/api/case_study_listing.py
digital_8848/digital_8848/doctype/case_study/case_study.json

added new field in case study button url

feat: added new field in case study button url

---

digital_8848/digital_8848/doctype/case_study/api/case_study_details.py
digital_8848/digital_8848/doctype/case_study/api/case_study_home_page.py
digital_8848/digital_8848/doctype/case_study/api/case_study_listing.py
digital_8848/digital_8848/doctype/case_study/case_study.json

button url changes in case study

fix: button url changes in case study

---

digital_8848/digital_8848/doctype/case_study/case_study.json
digital_8848/digital_8848/doctype/expertise/expertise.json
digital_8848/digital_8848/doctype/industry/industry.json
digital_8848/digital_8848/doctype/insights/insights.json
digital_8848/digital_8848/doctype/site_map/api/site_map.py
digital_8848/digital_8848/doctype/site_map/site_map.json
digital_8848/digital_8848/doctype/website_url_settings/website_url_settings.json

created sitemap settings and mapped for master doctypes

feat: created sitemap settings and mapped for master doctypes

---

digital_8848/digital_8848/doctype/case_study/case_study.json
digital_8848/digital_8848/doctype/expertise/api/expertise_details.py
digital_8848/digital_8848/doctype/expertise/expertise.json
digital_8848/digital_8848/doctype/industry/api/industry.py
digital_8848/digital_8848/doctype/industry/industry.json
digital_8848/digital_8848/doctype/site_map/api/site_map.py

added fields and changes in api

fix: added fields and changes in api

---

digital_8848/digital_8848/doctype/case_study/api/case_study_details.py
digital_8848/digital_8848/doctype/case_study/api/case_study_home_page.py
digital_8848/digital_8848/doctype/expertise/api/expertise_details.py
digital_8848/digital_8848/doctype/industry/api/industry.py

cta_btn_url added in details api

fix: cta_btn_url added in details api

---

digital_8848/digital_8848/doctype/case_study/api/case_study_details.py
digital_8848/digital_8848/doctype/case_study/api/case_study_home_page.py
digital_8848/digital_8848/doctype/case_study/api/case_study_listing.py
digital_8848/digital_8848/doctype/case_study/case_study.json
digital_8848/digital_8848/doctype/expertise/api/expertise_details.py
digital_8848/digital_8848/doctype/expertise/api/expertise_listing.py
digital_8848/digital_8848/doctype/expertise/expertise.json
digital_8848/digital_8848/doctype/industry/api/industry.py
digital_8848/digital_8848/doctype/industry/industry.json
digital_8848/digital_8848/doctype/insights/api/insights_details.py
digital_8848/digital_8848/doctype/insights/api/insights_listing.py

added new fields in doctype and in api

fix: added new fields in doctype and in api

---

digital_8848/digital_8848/doctype/site_map/site_map.json

changed sitemap doctype naming

fix: changed sitemap doctype naming

---

digital_8848/digital_8848/doctype/category/category.json
digital_8848/digital_8848/doctype/category/category.py

feat: Category

---

digital_8848/digital_8848/doctype/google_analytics/api/get_google_analytics.py
digital_8848/digital_8848/doctype/site_map/api/site_map.py

fix: Google Analytics
